version: "3.8"
services:
  django:
    build:
      context: ..
      dockerfile: docker\Dockerfile.core
    ports:
      - "8000:8000"
    environment:
      - STATIC_SERVE=0
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "80:80"
    depends_on:
      - django