services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  core:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.core
    container_name: sa_library_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
  mongo_data: