services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  core:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.core
    container_name: sa_library_backend
    environment:
      - CACHE_ENABLED=true
      - REDIS_URL=redis://redis:6379/0
    command: /bin/sh -c "python manage.py seed && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"

  mesos-master:
    image: mesosphere/mesos-master:1.7.1
    container_name: mesos-master
    environment:
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_PORT=5050
      - MESOS_CLUSTER=sa-library-cluster
    ports:
      - "5050:5050"
    depends_on:
      - zookeeper

  mesos-agent:
    image: mesosphere/mesos-slave:1.7.1
    container_name: mesos-agent
    environment:
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_PORT=5051
    ports:
      - "5051:5051"
    depends_on:
      - mesos-master
      - zookeeper

volumes:
  mongo_data: